"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Asset'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
properties:
  hosts:
    type: array
    items:
      type:
        - object
        - string
  isHostedBy:
    type:
      - object
      - string
  hasDeployment:
    type:
      - object
      - string
