"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Observation'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
allOf:
 - $ref: bblocks://ogc.sosa.properties.observation-owa
 - anyOf:
   - required:
     - hasResult
   - required:
     - hasSimpleResult
