"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Observation Feature'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
allOf:
  - $ref: bblocks://r1.geo.features.feature
  - $ref: ../../properties/observation/schema.yaml