"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Observation Feature'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
allOf:
  - $ref:  bblocks://ogc.geo.json-fg.feature-lenient
  - type: object
    properties:
      properties:
        $ref: ../../properties/observation/schema.yaml
