"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Observation'
'@modelReference': ../sosa-ssn.jsonld
type: object
properties:
  hasResult:
    type: object
  hasSimpleResult:
  resultTime:
    type: string
    format: date-time
  phenomenonTime:
    type:
      - object
      - string
  hasFeatureOfInterest:
    type:
      - object
      - string
  observedProperty:
    type:
      - object
      - string
  usedProcedure:
    type:
      - object
      - string
  madeBySensor:
    type:
      - object
      - string
required:
  - resultTime
  - hasFeatureOfInterest
oneOf:
  - hasResult
  - hasSimpleResult