"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA ObservationCollection'
x-jsonld-context: ../../../sosa-ssn.jsonld
$defs:
  oneOrMany:
    oneOf:
      - type:
        - object
        - string
      - type: array
        items:
          type:
            - object
            - string
  collection:
    allOf:
      - $ref: bblocks://ogc.sosa.properties.executionCollection
      - type: object
        properties:
          observedProperty:
            $ref: "#/$defs/oneOrMany"
          madeBySensor:
            $ref: "#/$defs/oneOrMany"
          hasMember:
            type: array
            items:
              anyOf:
                - $ref: '#/$defs/collection'
                - $ref: '../observation/schema.yaml'
                - $ref: bblocks://ogc.ogc-utils.iri-or-curie
allOf:
  - $ref: '#/$defs/collection'
  - not:
      anyOf:
        - required:
            - hasResult
        - required:
            - hasSimpleResult
