"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA ObservationCollection'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
properties:
  observations:
    $ref: ../observation/schema.yaml
anyOf:
  - required:
    - resultTime
  - required:
    - phenomenonTime
  - required:
    - hasFeatureOfInterest
  - required:
    - observedProperty
  - required:
    - usedProcedure
not:
  anyOf:
    - required:
        - hasResult
    - required:
        - hasSimpleResult
