"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Deployment'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
properties:
  deployedAsset:
    type:
      - object
      - string
  deployedOnPlatform:
    type:
      - object
      - string
  deployedSystem:
    type:
      - object
      - string
  hasFeatureOfInterest:
    type:
      - object
      - string
  startTime:
    type: string
    format: date-time
  endTime:
    type: string
    format: date-time
