"$schema": https://json-schema.org/draft/2020-12/schema
description: 'SOSA Sample'
x-jsonld-context: ../../../sosa-ssn.jsonld
type: object
properties:
  isSampleOf:
    type:
      - object
      - string
  isSampleOfUltimateFOI:
    type:
      - object
      - string
  hasOriginalSample:
    type:
      - object
      - string
  isOriginalSampleOf:
    type:
      - object
      - string
  isResultOfMadeBySampler:
    type:
      - object
      - string
  isResultOfUsedProcedure:
    type:
      - object
      - string
  isResultOf:
    type:
      - object
      - string
