"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Example SOSA Vector Observation'
allOf:
  - $ref: ../../properties/observation/schema.yaml
  - type: object
    properties:
      hasResult:
        properties:
          pose:
            $ref: bblocks://ogc.geo.geopose.basic.ypr
          distance:
            type: number
            x-jsonld-id: http://example.com/properties/distance
            x-jsonld-type: http://www.w3.org/2001/XMLSchema#float
    required:
      - hasResult
    not:
      required:
        - hasSimpleResult
