name: Validate and process Building Block
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  validate-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: OGC BB postprocess
        uses: opengeospatial/bblocks-postprocess/full@v1
        with:
          fail_on_error: 'true'
      - name: Add & Commit
        if: ${{ !endsWith(github.repository, '/bblock-template') }}
        uses: EndBug/add-and-commit@v9
        with:
          message: Building blocks postprocessing
